Run on Nodejs v18
epicweb-dev/rocket-rental pull request #20
Opened 2023-05-31 01:38 UTC by szepeviktor

The output has several warnings.
```
#10 1.827 npm WARN EBADENGINE Unsupported engine {
#10 1.827 npm WARN EBADENGINE   package: undefined,
#10 1.827 npm WARN EBADENGINE   required: { node: '18' },
#10 1.828 npm WARN EBADENGINE   current: { node: 'v16.20.0', npm: '8.19.4' }
#10 1.828 npm WARN EBADENGINE }
```

2023-06-01 20:20 UTC, kentcdodds requested changes
Thanks! Just one thing.

2023-06-01 20:20 UTC, kentcdodds commented on fly.toml
> +
I don't think this change is necessary.

```suggestion
```

2023-06-01 20:39 UTC, szepeviktor commented on fly.toml
> +
I agree.

2023-06-01 22:48 UTC, kentcdodds approved these changes
Thanks!

2023-06-01 22:48 UTC, merged

2023-06-02 01:30 UTC, szepeviktor commented
You're welcome.